detectors:
  UtilityFunction:
    public_methods_only: true
  TooManyStatements:
    max_statements: 10
  DuplicateMethodCall:
    max_calls: 3
  TooManyInstanceVariables:
    max_instance_variables: 5
  DataClump:
    max_copies: 3
  UncommunicativeVariableName:
    accept:
      - e
      - _

### Excluding directories

# Directories and files below will not be scanned at all
exclude_paths:
  - bin/*
